# Generated by Django 4.2.13 on 2024-05-31 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysodaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('counter_id', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('users', models.IntegerField()),
                ('visits', models.IntegerField()),
                ('pageviews', models.IntegerField()),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysodaapp.counter')),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
