# Generated by Django 4.2.13 on 2024-06-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysodaapp', '0002_counter_metricdata_delete_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
