# Generated by Django 4.2.13 on 2024-06-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysodaapp', '0003_visualization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='created_at',
        ),
        migrations.AddField(
            model_name='visualization',
            name='colors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='visualization',
            name='x_axis',
            field=models.CharField(default='date', max_length=255),
        ),
        migrations.AddField(
            model_name='visualization',
            name='y_axes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
